version: '3'

services:
  publicationservice:
    image: publicationservice
    build:
      context: .
      dockerfile: PublicationService/Dockerfile
    ports:
      - "8888:80"
    depends_on: 
      - rabbitmq

  consumerservice:
    image: consumerservice
    build:
      context: .
      dockerfile: ConsumerService/Dockerfile
    ports:
      - "8889:80"
    depends_on: 
      - rabbitmq
      - postgres

  rabbitmq:
    image: "rabbitmq:3-management"   
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"

  postgres:
    image: postgres:9.5
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=AdfenixTest
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "5432:5432"